//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Savelife
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> Mobile_Number { get; set; }
        public string Email_Id { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Blood_Type { get; set; }
        public string Landmark { get; set; }
        public string Password { get; set; }
        public string Confirm_Password { get; set; }
    }
}
